services:
  mongo:
    image: mongo:7
    container_name: biorehab_mongo
    restart: unless-stopped
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: biorehab
    volumes:
      - mongo_data:/data/db

  api:
    build: .
    container_name: biorehab_api
    restart: unless-stopped
    ports:
      - '3000:3000'
    depends_on:
      - mongo
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  mongo_data:
